### ISSUE TITLE
请问数据集是做的什么任务

### ISSUE THREAD

**Issue by shangzhensen** [yuanzhoulvpi2017/zero_nlp#1]
是生成任务吗？为什么我跑起来之后生成的东西很乱，而且任务不明确
![image](https://user-images.githubusercontent.com/48047942/220228222-f6016610-fd30-43aa-a7b6-236c0443f702.png)

**Comment by yuanzhoulvpi2017** [comment]
是生成任务。
效果不好主要是有下面几个问题：
1. gpt2模型问题
2. 训练的数据不够好。数据都太老了，而且也不多。

发自我的 iPhone

在 2023年2月21日，09:58，shangzhensen ***@***.***> 写道：

﻿

是生成任务吗？为什么我跑起来之后生成的东西很乱，而且任务不明确
[image]<https://user-images.githubusercontent.com/48047942/220228222-f6016610-fd30-43aa-a7b6-236c0443f702.png>
