### ISSUE TITLE
基于ChatGlm ptuning的也用了LoRA么？

### ISSUE THREAD

**Issue by qingyuan18** [yuanzhoulvpi2017/zero_nlp#105]
RT, 
https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/Chatglm6b_ModelParallel_ptuning, 这个也用了LoRA么？
simple question :)

**Comment by yuanzhoulvpi2017** [comment]
没有。ptuning和lora可以混用，但是没必要。
