### ISSUE TITLE
训练集测试集划分导致数据泄漏

### ISSUE THREAD

**Issue by yongqiangning** [yuanzhoulvpi2017/zero_nlp#108]
在read me里，明确写
train_data.csv,test_data.csv,valid_data.csv这三个数据里面，不要有数据相同的，不然会造成数据泄漏
但是文件code_01_processdata.ipynb 中train ,test, valid的划分方式明显有数据泄漏啊

**Comment by yuanzhoulvpi2017** [comment]
1. `readme.md`里面写`train_data.csv,test_data.csv,valid_data.csv这三个数据里面，不要有数据相同的`是为了：让人能知道这三个数据不要有重复的数据。
2. `但是文件code_01_processdata.ipynb 中train ,test, valid的划分方式明显有数据泄漏`是为了节约数据处理时间，图个省事。
