### ISSUE TITLE
遇到报错 RuntimeError: self and mat2 must have the same dtype

### ISSUE THREAD

**Issue by diaojunxian** [yuanzhoulvpi2017/zero_nlp#109]
在本地执行遇到问题：

![image](https://github.com/yuanzhoulvpi2017/zero_nlp/assets/19700467/f0034ed2-1dd2-4217-bce1-8d05d39ce027)

**Comment by yuanzhoulvpi2017** [comment]
查看代码https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/infer.ipynb的最下面。


example:
```python

text ="为什么冰红茶和柠檬茶的味道一样？"

with torch.autocast("cuda"):
    res, history = model.chat(tokenizer=tokenizer, query=text,max_length=300)
    print(res)
```
