### ISSUE TITLE
AttributeError: 'ChatGLMTokenizer' object has no attribute 'eop_token_id'

### ISSUE THREAD

**Issue by withyou971** [yuanzhoulvpi2017/zero_nlp#111]
ChatGLMTokenizer(name_or_path='model/chatglm-6b', vocab_size=130344, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='left', truncation_side='right', special_tokens={'bos_token': '<sop>', 'eos_token': '<eop>', 'unk_token': '<unk>', 'pad_token': '<pad>', 'mask_token': '[MASK]'})
这个是python版本不对吗，python3.10.6

**Comment by AIGroupOfDHCC** [comment]
我也发现了这个问题，引用其他地方的回答：

**Comment by AIGroupOfDHCC** [comment]
注意model_name_or_path的模型，要用我提供的模型

**Comment by AIGroupOfDHCC** [comment]
训练lora代码报错
AttributeError: 'ChatGLMTokenizer' object has no attribute 'eop_token_id'
[tokenizer.eop_token_id]
是不是应该改成
[tokenizer.sp_tokenizer[tokenizer.eos_token]]

**Comment by yuanzhoulvpi2017** [comment]
> 训练lora代码报错 AttributeError: 'ChatGLMTokenizer' object has no attribute 'eop_token_id' [tokenizer.eop_token_id] 是不是应该改成 [tokenizer.sp_tokenizer[tokenizer.eos_token]]

看清楚要求，使用的是`chatglm6b-dddd`。

**Comment by withyou971** [comment]
感谢，我下载这个试试

**Comment by PedroNeal** [comment]
> 感谢，我下载这个试试
![屏幕截图 2024-05-12 200400](https://github.com/yuanzhoulvpi2017/zero_nlp/assets/144669785/93177a0e-3606-4e70-bb7b-fa3aa714d6f1)


请问是怎么解决的
