### ISSUE TITLE
lora训练 多卡报错

### ISSUE THREAD

**Issue by aihaidong** [yuanzhoulvpi2017/zero_nlp#112]
我用仓库中的脚本，模型使用的是chatglm-6b试了很多次多卡报错都卡在这个地方
![image](https://github.com/yuanzhoulvpi2017/zero_nlp/assets/54533917/13186f1f-42f4-4c7e-845d-5c6152388107)

我按照readme方式，吧thuglm文件夹下的文件复制到模型文件中，报错如下：
![image](https://github.com/yuanzhoulvpi2017/zero_nlp/assets/54533917/f956d072-a62d-47cb-860f-50fed32e6472)

请问大佬我是需要指定张量的存放吗

**Comment by aihaidong** [comment]
我发现我的问题了，我用的新模型，用老模型就可以了

**Comment by Ardang666** [comment]
最后用的是个 commit的模型啊，用作者截图的commit，也跑不了

**Comment by Ardang666** [comment]
用 dddd 可以跑起来
