### ISSUE TITLE
README 里有一处笔误

### ISSUE THREAD

**Issue by shtdbb** [yuanzhoulvpi2017/zero_nlp#13]
但是，你在从github上下载我这个仓库后，是看不到这几个文件的：

pytorch_model-00001-of-00008.bin、
pytorch_model-00002-of-00008.bin、
pytorch_model-00002-of-00008.bin、
pytorch_model-00003-of-00008.bin、
pytorch_model-00004-of-00008.bin、
pytorch_model-00005-of-00008.bin、
pytorch_model-00006-of-00008.bin、
pytorch_model-00007-of-00008.bin、
pytorch_model-00008-of-00008.bin、
ice_text.model

-----------------------------------------------------------------------------
这段第二个多重复了一次哈哈

**Comment by yuanzhoulvpi2017** [comment]
已经修改啦，哈哈哈哈
