### ISSUE TITLE
bloom 也是 casulmModel 体系下的，是否可以用cpu加速推理

### ISSUE THREAD

**Issue by xx-zhang** [yuanzhoulvpi2017/zero_nlp#133]
bloom 也是 casulmModel 体系下的，是否可以用cpu加速推理； 就是用avx2, avx512的指令加速推理。我看有个bloom.cpp 但是速度没有lamma.cpp那个快（同样 7b int8) . 这个是什么原因？

**Comment by yuanzhoulvpi2017** [comment]
在cpu上推理，这个还真没研究过～
