### ISSUE TITLE
求助：chatglm2 lora训练error：RuntimeError: Expected is_sm80 to be true, but got false.

### ISSUE THREAD

**Issue by thirttyyy** [yuanzhoulvpi2017/zero_nlp#152]
你好，按照readme，transformers库已经更新到最新，报错信息如下：
```
RuntimeError: Expected is_sm80 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```
用的是一张A40卡，应该如何修改呢？

**Comment by cobedry** [comment]
修改的哪个文件

**Comment by jakeywu** [comment]
https://github.com/pytorch/pytorch/issues/94883
pip install --force-reinstall --pre torch --index-url https://download.pytorch.org/whl/nightly/cu117
我更换了torch版本就可以了
