### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by pollymars** [yuanzhoulvpi2017/zero_nlp#18]
微调训练刚开始时遇到 TypeError: 'NoneType' object is not subscriptable
问题出在modeling_chatglm的173行，计算自注意层rotary_emb时，cos_cached和sin_cached被初始化为None了，然后大概是这两个被直接用到。
不清楚是数据问题还是什么问题？设备P100

**Comment by yuanzhoulvpi2017** [comment]
感谢提出宝贵的issue。这个问题我在我的服务器上也遇到了（是两台T4显卡）。

这个点我也在`readme.md`里面提到了[https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b#%EF%B8%8F%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9](https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b#%EF%B8%8F%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)

目前，我还没想好怎么解决。多半是我的代码问题，目前还在调试中

**Comment by yuanzhoulvpi2017** [comment]
帅哥，我现在已经把代码更新了，你再跑试一试。
