### ISSUE TITLE
llava合并模型后加载推理报错

### ISSUE THREAD

**Issue by daihuidai** [yuanzhoulvpi2017/zero_nlp#180]
你好，我跟着zero/nlp/train_llava/code03_build_model_show.ipynb完成了模型的合并，但是在加载时报了下面这个问题，请问是什么问题呢？

![image](https://github.com/yuanzhoulvpi2017/zero_nlp/assets/43409147/940e274a-fe88-40be-a179-c4fc5bdacae7)

**Comment by yuanzhoulvpi2017** [comment]
是已经解决了是么？

**Comment by daihuidai** [comment]
@yuanzhoulvpi2017 是的解决了
