### ISSUE TITLE
关于train_llava中processor的疑问。

### ISSUE THREAD

**Issue by weiaicunzai** [yuanzhoulvpi2017/zero_nlp#189]
谢谢你的代码。我想请教一下，我在train_llava加载数据集的时候，autoprocessor部分，我选择加载 model002 文件夹和 model001文件夹之间，有区别吗？我的理解是auto processor只是关于处理图像部分的代码（例如resize，flip， jitter操作）的定义。

**Comment by yuanzhoulvpi2017** [comment]
这个你可以看一下我的视频，细节我也记不太清楚了～
