### ISSUE TITLE
Train_llava。 缺少preprocessor_config.json. 文件。

### ISSUE THREAD

**Issue by weiaicunzai** [yuanzhoulvpi2017/zero_nlp#199]
你好，我按照您的代码，写完训练后，再加载推理的时候跟我说 does not appear to have a file named preprocessor_config.json。是不是因为trainer没有传入processor参数导致的？

https://github.com/yuanzhoulvpi2017/zero_nlp/blob/fb4ba1c7c480a900cce9226cf4e53b023334d48c/train_llava/run.py#L126

**Comment by yuanzhoulvpi2017** [comment]
你这是复制的文件不对。

**Comment by yuanzhoulvpi2017** [comment]
https://github.com/yuanzhoulvpi2017/zero_nlp/issues/185#issuecomment-2543705064

**Comment by yuanzhoulvpi2017** [comment]
建议到我的这个模型下，对比一下几个config文件，很有可能你是复制错config文件了📄https://huggingface.co/yuanzhoulvpi/llava_qwen15-4b-chat_openai-clip-vit-large-patch14-336/tree/main
