### ISSUE TITLE
我使用自定义样本出错了，是样本里面的size太大了么 chatglm-6b lora

### ISSUE THREAD

**Issue by xx-zhang** [yuanzhoulvpi2017/zero_nlp#20]
![image](https://user-images.githubusercontent.com/47806549/227966967-43826e00-44e1-4252-a482-7b6c52c8e76c.png)

**Comment by xx-zhang** [comment]
![image](https://user-images.githubusercontent.com/47806549/227967629-8c80ff77-a56e-4f91-be85-8feab32a576c.png)

**Comment by zhaodice** [comment]
样本是不是有点少（

**Comment by xx-zhang** [comment]
> 样本是不是有点少（

回头试试，不过我对我这个数据源已经不抱希望了，准备重新换一个。 应该是修改 cotent的格式问题，或者是每行太长了，毕竟都是1Mb+的大小
