### ISSUE TITLE
Train_Llava

### ISSUE THREAD

**Issue by xupengfei-dr** [yuanzhoulvpi2017/zero_nlp#203]
根据up的视频我showmodel里model001从model002拿过来的preprocessor.config中的"processor_class": "CLIPTokenizerFast"。但是up里面的是"processor_class": "LlavaProcessor"。 我在使用processor.tokenizer时候是加载为了CLIPTokenizerFast。这里要把我的preprocessor.config中的CLIPTokenizerFast改一下吗？ 求解答

**Comment by yuanzhoulvpi2017** [comment]
不应该吧，正常的这个processor肯定是llavaprocessor的，你是不是漏了一步。

**Comment by xupengfei-dr** [comment]
autoprocessor = AutoProcessor.from_pretrained(clip_model_name_or_path)
autoprocessor.save_pretrained("show_model/model002") 我的这个AutoProcessor 被匹配成了CLIPProcessor ，我用autoprocessor = LlavaProcessor.from_pretrained(clip_model_name_or_path) 就对了

**Comment by yuanzhoulvpi2017** [comment]
好兄弟，仔细看看我视频，一般不会出现这样问题的吧～🥺

**Comment by xupengfei-dr** [comment]
isok
