### ISSUE TITLE
train_chatglm6b.py 可以使用alpaca数据集格式吗？

### ISSUE THREAD

**Issue by chenyiwan** [yuanzhoulvpi2017/zero_nlp#25]
train_chatglm6b.py data2 目录下的csv文件，都是一个字段content,这个字段内容就放纯文本就行吗？

另外，这个可以使用alpaca数据集格式吗？

**Comment by yuanzhoulvpi2017** [comment]
可以的，目前我正在整理教程，稍后放出来

**Comment by yuanzhoulvpi2017** [comment]
目前已经更新，可以使用这个文件来训练[https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/code02_%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%85%A8%E9%83%A8%E6%B5%81%E7%A8%8B.ipynb](https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/code02_%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%85%A8%E9%83%A8%E6%B5%81%E7%A8%8B.ipynb)
