### ISSUE TITLE
能给出来安装包以及依赖环境得配置嘛？ 各种报错

### ISSUE THREAD

**Issue by zbbwss** [yuanzhoulvpi2017/zero_nlp#26]
![image](https://user-images.githubusercontent.com/42829645/228241720-2a530115-8c36-43d2-9939-a7821cc55284.png)

**Comment by zbbwss** [comment]
![image](https://user-images.githubusercontent.com/42829645/228242526-749ffba4-9813-4c4d-97d0-89e5549ddb60.png)

**Comment by chenyiwan** [comment]
Package                  Version
------------------------ ----------
accelerate               0.18.0
aiohttp                  3.8.4
aiosignal                1.3.1
async-timeout            4.0.2
asynctest                0.13.0
attrs                    22.2.0
certifi                  2022.12.7
charset-normalizer       3.1.0
cpm-kernels              1.0.11
datasets                 2.10.1
DBUtils                  3.0.2
dill                     0.3.6
filelock                 3.10.7
frozenlist               1.3.3
fsspec                   2023.1.0
gpt-db-tools             0.0.1
huggingface-hub          0.13.3
icetk                    0.0.4
idna                     3.4
importlib-metadata       6.1.0
multidict                6.0.4
multiprocess             0.70.14
numpy                    1.21.6
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.0
pandas                   1.3.5
peft                     0.2.0
Pillow                   9.4.0
pip                      22.0.4
protobuf                 3.20.0
psutil                   5.9.4
psycopg2-binary          2.9.5
pyarrow                  11.0.0
python-dateutil          2.8.2
pytz                     2023.2
PyYAML                   6.0
regex                    2022.10.31
requests                 2.28.2
responses                0.18.0
sentencepiece            0.1.97
setuptools               47.1.0
six                      1.16.0
tokenizers               0.13.2
torch                    1.13.1
torchvision              0.14.1
tqdm                     4.65.0
transformers             4.26.1
typing_extensions        4.5.0
urllib3                  1.26.15
wheel                    0.40.0
xxhash                   3.2.0
yarl                     1.8.2
zipp                     3.15.0

**Comment by zbbwss** [comment]
跑通了  感觉不是你的问题！感谢楼主 是我自己环境的配置的事情 感谢楼主的热情分享！ 点赞
