### ISSUE TITLE
多卡微调报错呢

### ISSUE THREAD

**Issue by chenyiwan** [yuanzhoulvpi2017/zero_nlp#28]
return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)

**Comment by chenyiwan** [comment]
我这里有8张P40, 我尝试改了
export CUDA_VISIBLE_DEVICES=0,1,2,3 又是另外一个错

RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 23.88 GiB total capacity; 11.69 GiB already allocated; 5.81 MiB free; 11.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by chenyiwan** [comment]
发现问题了，你自己修改了 tokenization_chatglm.py这个文件的。。。我没注意，直接 用的原版的。。

**Comment by chenyiwan** [comment]
File "/home/thudm/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 864, in forward
    logger.warning_once(
AttributeError: 'Logger' object has no attribute 'warning_once'
小白调试，一步一个坑。。。
为什么没有使用你修改后的文件呢。。。

**Comment by pollymars** [comment]
> File "/home/thudm/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 864, in forward logger.warning_once( AttributeError: 'Logger' object has no attribute 'warning_once' 小白调试，一步一个坑。。。 为什么没有使用你修改后的文件呢。。。

这个bug我也遇到过，我是把warning_once改成info了

**Comment by chenyiwan** [comment]
> > File "/home/thudm/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 864, in forward logger.warning_once( AttributeError: 'Logger' object has no attribute 'warning_once' 小白调试，一步一个坑。。。 为什么没有使用你修改后的文件呢。。。
> 
> 这个bug我也遇到过，我是把warning_once改成info了

关键是你看他用的原版的这个文件 ，没用up主改后的那个。。。。

**Comment by chenyiwan** [comment]
> > File "/home/thudm/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 864, in forward logger.warning_once( AttributeError: 'Logger' object has no attribute 'warning_once' 小白调试，一步一个坑。。。 为什么没有使用你修改后的文件呢。。。
> 
> 这个bug我也遇到过，我是把warning_once改成info了

可以了，我也改了一下。。

**Comment by xiamaozi11** [comment]
> return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)

同学改好了么

**Comment by chenyiwan** [comment]
> 

好了，正常跑起来了

**Comment by chenyiwan** [comment]
> > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> 
> 同学改好了么
好了，正常跑起来了

**Comment by xiamaozi11** [comment]
> > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > 
> > 
> > 同学改好了么
> > 好了，正常跑起来了

能说下改哪里么

**Comment by chenyiwan** [comment]
> > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > 
> > > 
> > > 同学改好了么
> > > 好了，正常跑起来了
> 
> 能说下改哪里么

你要用他提供thuglm下的几个py文件

**Comment by xiamaozi11** [comment]
ok

**Comment by zhangzai666** [comment]
> > > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > > 
> > > > 
> > > > 同学改好了么
> > > > 好了，正常跑起来了
> > 
> > 
> > 能说下改哪里么
> 
> 你要用他提供thuglm下的几个py文件

大神问一下，微调的时候报错：
RuntimeError: Caught RuntimeError in replica 1 on device 1.
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
这个遇到过么，怎么改一下啊

**Comment by chenyiwan** [comment]
> 

![image](https://user-images.githubusercontent.com/56297473/228419145-3c973407-581a-4c33-8fa6-70a88c16e79d.png)
你用他这个目录下的文件，把原来的bin复制进来，还有那个词表文件 ice_txt.bin 就行了。

**Comment by chenyiwan** [comment]
> > > > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > > > 
> > > > > 
> > > > > 同学改好了么
> > > > > 好了，正常跑起来了
> > > 
> > > 
> > > 能说下改哪里么
> > 
> > 
> > 你要用他提供thuglm下的几个py文件
> 
> 大神问一下，微调的时候报错： RuntimeError: Caught RuntimeError in replica 1 on device 1. RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) 这个遇到过么，怎么改一下啊

![image](https://user-images.githubusercontent.com/56297473/228419253-05515a1e-eda7-47fd-9ff2-2ec48bea04b0.png)
你用他这个目录下的文件，把原来的bin复制进来，还有那个词表文件 ice_txt.bin 就行了。

**Comment by xiamaozi11** [comment]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by 1006076811** [comment]
> RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

同学我也遇到这个问题，有什么解决方案吗

**Comment by zhangzai666** [comment]
> > > > > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > > > > 
> > > > > > 
> > > > > > 同学改好了么
> > > > > > 好了，正常跑起来了
> > > > 
> > > > 
> > > > 能说下改哪里么
> > > 
> > > 
> > > 你要用他提供thuglm下的几个py文件
> > 
> > 
> > 大神问一下，微调的时候报错： RuntimeError: Caught RuntimeError in replica 1 on device 1. RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) 这个遇到过么，怎么改一下啊
> 
> ![image](https://user-images.githubusercontent.com/56297473/228419253-05515a1e-eda7-47fd-9ff2-2ec48bea04b0.png) 你用他这个目录下的文件，把原来的bin复制进来，还有那个词表文件 ice_txt.bin 就行了。

感谢您的回答，现在又报了新的错误。
ValueError: Caught ValueError in replica 1 on device 1.
ValueError: 150001 is not in list
![image](https://user-images.githubusercontent.com/94370914/228434323-94b85234-9c95-4141-b68f-740b7f61910a.png)

**Comment by chenyiwan** [comment]
> > > > > > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > > > > > 
> > > > > > > 
> > > > > > > 同学改好了么
> > > > > > > 好了，正常跑起来了
> > > > > 
> > > > > 
> > > > > 能说下改哪里么
> > > > 
> > > > 
> > > > 你要用他提供thuglm下的几个py文件
> > > 
> > > 
> > > 大神问一下，微调的时候报错： RuntimeError: Caught RuntimeError in replica 1 on device 1. RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) 这个遇到过么，怎么改一下啊
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56297473/228419253-05515a1e-eda7-47fd-9ff2-2ec48bea04b0.png) 你用他这个目录下的文件，把原来的bin复制进来，还有那个词表文件 ice_txt.bin 就行了。
> 
> 感谢您的回答，现在又报了新的错误。 ValueError: Caught ValueError in replica 1 on device 1. ValueError: 150001 is not in list ![image](https://user-images.githubusercontent.com/94370914/228434323-94b85234-9c95-4141-b68f-740b7f61910a.png)

你试试设置 export CUDA_VISIBLE_DEVICES=0

**Comment by zhangzai666** [comment]
> > > > > > > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 同学改好了么
> > > > > > > > 好了，正常跑起来了
> > > > > > 
> > > > > > 
> > > > > > 能说下改哪里么
> > > > > 
> > > > > 
> > > > > 你要用他提供thuglm下的几个py文件
> > > > 
> > > > 
> > > > 大神问一下，微调的时候报错： RuntimeError: Caught RuntimeError in replica 1 on device 1. RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) 这个遇到过么，怎么改一下啊
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/56297473/228419253-05515a1e-eda7-47fd-9ff2-2ec48bea04b0.png) 你用他这个目录下的文件，把原来的bin复制进来，还有那个词表文件 ice_txt.bin 就行了。
> > 
> > 
> > 感谢您的回答，现在又报了新的错误。 ValueError: Caught ValueError in replica 1 on device 1. ValueError: 150001 is not in list ![image](https://user-images.githubusercontent.com/94370914/228434323-94b85234-9c95-4141-b68f-740b7f61910a.png)
> 
> 你试试设置 export CUDA_VISIBLE_DEVICES=0

还是不行，看这个意思是列表没有1500001这个元素，上面报错好像是显卡显存问题，我有4张40G的显卡，按理说不应该。这个是因为多卡训练的问题么，代码我还没仔细看，直接报了很多错

**Comment by chenyiwan** [comment]
多张训练，为何总是第一张卡负载90%多，其它闲着呢。

**Comment by yuanzhoulvpi2017** [comment]
> > > > > > > > > > return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 同学改好了么
> > > > > > > > > 好了，正常跑起来了
> > > > > > > 
> > > > > > > 
> > > > > > > 能说下改哪里么
> > > > > > 
> > > > > > 
> > > > > > 你要用他提供thuglm下的几个py文件
> > > > > 
> > > > > 
> > > > > 大神问一下，微调的时候报错： RuntimeError: Caught RuntimeError in replica 1 on device 1. RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select) 这个遇到过么，怎么改一下啊
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/56297473/228419253-05515a1e-eda7-47fd-9ff2-2ec48bea04b0.png) 你用他这个目录下的文件，把原来的bin复制进来，还有那个词表文件 ice_txt.bin 就行了。
> > > 
> > > 
> > > 感谢您的回答，现在又报了新的错误。 ValueError: Caught ValueError in replica 1 on device 1. ValueError: 150001 is not in list ![image](https://user-images.githubusercontent.com/94370914/228434323-94b85234-9c95-4141-b68f-740b7f61910a.png)
> > 
> > 
> > 你试试设置 export CUDA_VISIBLE_DEVICES=0
> 
> 还是不行，看这个意思是列表没有1500001这个元素，上面报错好像是显卡显存问题，我有4张40G的显卡，按理说不应该。这个是因为多卡训练的问题么，代码我还没仔细看，直接报了很多错

是不是词表下载的不对？

**Comment by xiaoweiweixiao** [comment]
> > RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 同学我也遇到这个问题，有什么解决方案吗



> RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

我也遇到这个问题了，你们解决了吗？
![image](https://user-images.githubusercontent.com/35003110/228715982-ad1e9417-68e6-40cc-acb2-de77e4da871e.png)

**Comment by yuanzhoulvpi2017** [comment]
添加了单机多卡训练代码，链接放在这里，https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/Chatglm6b_ModelParallel
