### ISSUE TITLE
参考最新的微调alpaca数据集报错

### ISSUE THREAD

**Issue by zhangzai666** [yuanzhoulvpi2017/zero_nlp#30]
RuntimeError: Caught RuntimeError in replica 1 on device 1.
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)

**Comment by zhangzai666** [comment]
参考一个大哥解决了这个问题，又出现了新的问题如下：
![image](https://user-images.githubusercontent.com/94370914/228434508-4018d426-7bab-45bc-9d2b-679c7a25f81a.png)

**Comment by yuanzhoulvpi2017** [comment]
哎，很奇怪，怎么会出现这样的错误。和隔壁的错误好像。好家伙，两个人都是你
