### ISSUE TITLE
作者您好，希望您解答一下我的问题，谢谢

### ISSUE THREAD

**Issue by zhangzai666** [yuanzhoulvpi2017/zero_nlp#32]
您好，非常高兴看到这么优秀简练的项目。我微调您更新的alpaca数据集代码报了一下错误，希望得到您的解答
![image](https://user-images.githubusercontent.com/94370914/228447591-5c823292-8541-49db-b8c7-79fadce72b14.png)

**Comment by zhangzai666** [comment]
> 1. 检查一下。是不是使用的是我的那个model文件
> 2. 检查一下，是不是使用的是https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/code02_%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%85%A8%E9%83%A8%E6%B5%81%E7%A8%8B.ipynb

感谢您的解答，我是参考的如上这个文件。请问您说的model文件是哪个，我是参考您之前的步骤去huggace上的模型00001-00008和ice_text.model词表文件。然后报了如上错误。应该是感觉词表越界，但是我加载tokenizer后发现其vocab_size=150034，大于这个150001,然后我发现150001对应的词是mask，另外我发现您的代码中有from thuglm.modeling_chatglm import ChatGLMForConditionalGeneration这个是用来加载模型的吧，但是没有用上，还是用的model = AutoModel.from_pretrained(
    "thuglm", trust_remote_code=True).half().cuda()加载模型
    感谢你的解答

**Comment by yuanzhoulvpi2017** [comment]
> > 1. 检查一下。是不是使用的是我的那个model文件
> > 2. 检查一下，是不是使用的是https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/code02_%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%85%A8%E9%83%A8%E6%B5%81%E7%A8%8B.ipynb
> 
> 感谢您的解答，我是参考的如上这个文件。请问您说的model文件是哪个，我是参考您之前的步骤去huggace上的模型00001-00008和ice_text.model词表文件。然后报了如上错误。应该是感觉词表越界，但是我加载tokenizer后发现其vocab_size=150034，大于这个150001,然后我发现150001对应的词是mask，另外我发现您的代码中有from thuglm.modeling_chatglm import ChatGLMForConditionalGeneration这个是用来加载模型的吧，但是没有用上，还是用的model = AutoModel.from_pretrained( "thuglm", trust_remote_code=True).half().cuda()加载模型 感谢你的解答

两个一样的，只要是用了我提供的`modeling_chatglm.py`即可。两个加载方式不同，但是本质上差不多。

你尝试换个别的数据试一试（难道是使用我提供的数据，出现了这个问题嘛，不应该呀）

**Comment by zhangzai666** [comment]
感谢您的解答，感觉是input_ids里面没有包含gmaks的缘故，我简单的将报错的代码调整为：
![image](https://user-images.githubusercontent.com/94370914/228566800-d28a507e-a500-4ed5-93e3-96f9e48f373d.png)
结果报错
![image](https://user-images.githubusercontent.com/94370914/228566560-1ef9c9a1-778d-44e8-9c08-e55db2de965c.png)
查了一下这个可能是barch_size设置太大，但是我设置为1还是不行，估计还是上面问题导致的
有时间我详细拜读您的代码，感谢您的解答

**Comment by zhangzai666** [comment]
> > > 1. 检查一下。是不是使用的是我的那个model文件
> > > 2. 检查一下，是不是使用的是https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/code02_%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%85%A8%E9%83%A8%E6%B5%81%E7%A8%8B.ipynb
> > 
> > 
> > 感谢您的解答，我是参考的如上这个文件。请问您说的model文件是哪个，我是参考您之前的步骤去huggace上的模型00001-00008和ice_text.model词表文件。然后报了如上错误。应该是感觉词表越界，但是我加载tokenizer后发现其vocab_size=150034，大于这个150001,然后我发现150001对应的词是mask，另外我发现您的代码中有from thuglm.modeling_chatglm import ChatGLMForConditionalGeneration这个是用来加载模型的吧，但是没有用上，还是用的model = AutoModel.from_pretrained( "thuglm", trust_remote_code=True).half().cuda()加载模型 感谢你的解答
> 
> 两个一样的，只要是用了我提供的`modeling_chatglm.py`即可。两个加载方式不同，但是本质上差不多。
> 
> 你尝试换个别的数据试一试（难道是使用我提供的数据，出现了这个问题嘛，不应该呀）

作者您好，我怀疑可能是多卡的原因，请问如何改成单卡

**Comment by alin995** [comment]
我也是多卡的问题，试试下面的设置
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

**Comment by zhangzai666** [comment]
> 

您好，我原来os.environ["CUDA_VISIBLE_DEVICES"] = "1"，不行。改成os.environ["CUDA_VISIBLE_DEVICES"] = "0"可以了。十分感谢。之前模型直接加载到4张卡，0号卡的负载多。这次直接全在0号卡上就可以跑通了。具体细节我还没看。多谢了兄弟

**Comment by yuanzhoulvpi2017** [comment]
> > 
> 
> 您好，我原来os.environ["CUDA_VISIBLE_DEVICES"] = "1"，不行。改成os.environ["CUDA_VISIBLE_DEVICES"] = "0"可以了。十分感谢。之前模型直接加载到4张卡，0号卡的负载多。这次直接全在0号卡上就可以跑通了。具体细节我还没看。多谢了兄弟

添加了单机多卡训练代码，链接放在这里，https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/Chatglm6b_ModelParallel
