### ISSUE TITLE
双卡3090微调aplace，有没有人遇到这个问题

### ISSUE THREAD

**Issue by 1079863482** [yuanzhoulvpi2017/zero_nlp#34]
训练过程中突然就断了，或者一开始的时候就断了。

主要报错信息如下：

![image](https://user-images.githubusercontent.com/52614226/228566091-8b03d94b-c744-4086-b346-8ccb7df535af.png)

下面还有一部分：
![image](https://user-images.githubusercontent.com/52614226/228566550-264d76cf-2457-42c9-9dd5-cac3d13ec196.png)

环境：
1. python 3.8
2. cuda 11.6
3. pytorch 2.0

**Comment by Alternate-D** [comment]
> 

兄弟我和你问题一模一样，也不知道怎么搞

**Comment by 1006076811** [comment]
我和您的问题一样，cuda版本11.3。4卡微调

**Comment by yuanzhoulvpi2017** [comment]
已留意～

**Comment by 1079863482** [comment]
单卡跑没问题，现在用双卡会报以上错，如果单卡跑也会报上面错的话，建议把原来conda虚拟环境删掉重新创建一个，hub中的pip install来

**Comment by yuanzhoulvpi2017** [comment]
目前多卡确实会出现问题，sorry～，我还在优化。
其实我自己都在怀疑，之前的多卡版本是好的，但是我就稍微改了一下代码，并行功能就丧失了，哎

**Comment by yuanzhoulvpi2017** [comment]
添加了单机多卡训练代码，链接放在这里，https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/Chatglm6b_ModelParallel
