### ISSUE TITLE
微调后的checkpoint 能保存为原来的bin格式的文件吗？

### ISSUE THREAD

**Issue by chenyiwan** [yuanzhoulvpi2017/zero_nlp#36]
simple_thu_chatglm6b
微调后的checkpoint 能保存为原来的bin格式的文件吗？

**Comment by alin995** [comment]
试试下面代码：
trainer = Trainer(
    model=model,
    tokenizer=tokenizer,
    args=args,
    data_collator=data_collator,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["valid"],
)
trainer.train()
