### ISSUE TITLE
微调后怎么启动一个api server供外部调用？

### ISSUE THREAD

**Issue by bh4ffu** [yuanzhoulvpi2017/zero_nlp#37]
请问，微调后怎么启动一个api server供外部调用？

**Comment by bh4ffu** [comment]
https://github.com/THUDM/ChatGLM-6B/blob/main/api.py

**Comment by bh4ffu** [comment]
https://github.com/THUDM/ChatGLM-6B/blob/main/api.py
准备参考这里的写法

**Comment by chenyiwan** [comment]
自己写一个flask ，web服务就行了
