### ISSUE TITLE
可以增量训练么？

### ISSUE THREAD

**Issue by bh4ffu** [yuanzhoulvpi2017/zero_nlp#47]
大家有没有增量训练的思路或者资料分享一下，不胜感激:)

**Comment by yanchaoguo** [comment]
> 大家有没有增量训练的思路或者资料分享一下，不胜感激:)

了解下lora技术

**Comment by reborm** [comment]
> 

请问完成增量训练了吗？我目前的数据是增量更新的，也比较疑惑怎么用Lora进行增量寻来呢
