### ISSUE TITLE
如何给ChatGLM-6B增加特定领域的知识，然后根据这些知识来问答

### ISSUE THREAD

**Issue by Mr-IT007** [yuanzhoulvpi2017/zero_nlp#48]
我想给ChatGLM-6B增加特定领域的知识，这些知识可能是很多段的大量文本内容，然后根据这些知识来问答，应该怎么做呢

**Comment by chenyiwan** [comment]
这不就是fine-tuning吗

**Comment by Mr-IT007** [comment]
> 这不就是fine-tuning吗

就是我要把所有的文本内容转成训练数据的格式来训练吗

**Comment by bh4ffu** [comment]
fine-tuning，参考如下
1）[训练](https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/code02_%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E5%85%A8%E9%83%A8%E6%B5%81%E7%A8%8B.ipynb)
2）[推理](https://github.com/yuanzhoulvpi2017/zero_nlp/blob/main/simple_thu_chatglm6b/infer.ipynb)

good luck~
