### ISSUE TITLE
训练后的模型不能像chatglm-6B中生成的模型一样被加载成为接口。报输入形状错误。

### ISSUE THREAD

**Issue by natureLanguageQing** [yuanzhoulvpi2017/zero_nlp#55]
![image](https://user-images.githubusercontent.com/37429336/229675384-3a981ec5-2422-40b3-bae6-ddc931c1c33e.png)
x训练后的模型不能像chatglm-6B中生成的模型一样被加载成为接口。报输入形状错误。

**Comment by xxyp** [comment]
你好，请问这个问题你解决了吗
