### ISSUE TITLE
关于训练集数据的疑惑

### ISSUE THREAD

**Issue by zhaodice** [yuanzhoulvpi2017/zero_nlp#6]
看了训练数据集是那种无格式的一维文本数据。
但是ChatGLM看起来似乎是用这种数据格式训练的
```
 prompt += "[Round {}]\n问：{}\n答：".format(len(history), query)
```
例如，ChatGLM团队给AI训练的语料应该是类似:
```
[Round 1]问：睡不着。
答：数到114514个绵羊即可睡着。
```
那么用户输入"睡不着。"的时候，输入给模型的内容实质上是:
```
[Round 1]问：睡不着。
答：
````
模型根据之前的训练，自动补充了接下来的内容，从而作为聊天回复结果(也就是推测出答后面应该是什么)

但你的训练集，并没有遵循上述格式，甚至和对话一点关系都没有，比较好奇会出什么样的结果，能达到什么效果?丰富问答语料还是补充模型知识?…纯新手，只是有点疑惑

**Comment by yuanzhoulvpi2017** [comment]
一回事，本质上就是文本拼接成一条。我那个数据，也就是一个demo

**Comment by fotomxq** [comment]
那是否可以理解成，采用chatGLM语料的格式，也是可以的？

**Comment by yuanzhoulvpi2017** [comment]
当然可以滴

发自我的 iPhone

在 2023年3月23日，08:23，liuzilu ***@***.***> 写道：

﻿

那是否可以理解成，采用chatGLM语料的格式，也是可以的？

**Comment by zhaodice** [comment]
> 一回事，本质上就是文本拼接成一条。我那个数据，也就是一个demo

那么按照demo的那种"格式"，也就是把各种聊天记录啦，文案啦，塞进content列表里，没有问答那种格式，会对模型的对话情况产生何种影响呢?

**Comment by nuoma** [comment]
同样非常困惑这个都是新闻的训练数据的作用是什么。我的理解是这个stage应该是找规律，所以training data应该是新的任务（规律），而不是给他增加新的领域知识

**Comment by zhaodice** [comment]
> 同样非常困惑这个都是新闻的训练数据的作用是什么。我的理解是这个stage应该是找规律，所以training data应该是新的任务（规律），而不是给他增加新的领域知识

也就是说，如果我训练了大量的

```
研究表明，。。。
报告指出，。。。
曾说，。。。
```
那么我和只需要和AI对话“请补充内容：研究指出，”
AI就能自动根据之前训练的内容，帮我完善内容了

**Comment by zhangtaochn** [comment]
我理解目前代码是对于ChatGLM灌领域的无监督数据，增强在某一个领域的效果， 另外，相比较chatGPT还需要RLHF监督数据做进一步训练对么， @yuanzhoulvpi2017

**Comment by ToSev7en** [comment]
推荐试试 ALPACA 翻译成中文的数据
