### ISSUE TITLE
'ChatGLM Tokenizer' object has no attribute 'eos_token_id'

### ISSUE THREAD

**Issue by OneStepAndTwoSteps** [yuanzhoulvpi2017/zero_nlp#67]
是chatglm更新的太快了吗，早上还可以正常运行的代码下午就报错了

**Comment by gaoyangthu** [comment]
同样的报错，请问如何修正？

**Comment by yuanzhoulvpi2017** [comment]
这个好像是官方代码问题。我看昨晚上，代码又更新了。你再试一试？


<img width="1792" alt="截屏2023-04-12 10 21 12" src="https://user-images.githubusercontent.com/30610553/231331300-25a5c00e-82c7-4f87-a332-a6f49c84e8a3.png">

**Comment by valkryhx** [comment]
今天下午尝试chatglm-6b-int4
同样有这个问题

**Comment by yuanzhoulvpi2017** [comment]
哪一个文件夹下的问题，报给我一下。

**Comment by liyanallen** [comment]
<img width="632" alt="1681732307816" src="https://user-images.githubusercontent.com/41948207/232476237-96c54448-7b09-4f11-8237-e9e981b40134.png">
<img width="692" alt="1681732359592" src="https://user-images.githubusercontent.com/41948207/232476446-3923da6e-2509-4d93-9ba3-3a13f09a191b.png">

**Comment by liyanallen** [comment]
thank u very much

**Comment by yuanzhoulvpi2017** [comment]
留意一下，我`04-16`发布的版本https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b#04-16-%E7%89%88%E6%9C%AC 我自己维护了一套chatglm6b模型

**Comment by liyanallen** [comment]
> 留意一下，我`04-16`发布的版本https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b#04-16-%E7%89%88%E6%9C%AC 我自己维护了一套chatglm6b模型

It does work, thank u very much
