### ISSUE TITLE
chatglm不可以自动层并行吗？

### ISSUE THREAD

**Issue by kevinuserdd** [yuanzhoulvpi2017/zero_nlp#74]
model = AutoModel.from_pretrained("chatglm-6b",device_map='auto')
这样的写法在多卡上面是无法实现吗？ 有的模型是可以的

**Comment by kevinuserdd** [comment]
> 这个在别的issue里面写过了，chatglm目前不支持～

非常感谢，终于得到想要的答案； 另外请教下，我用deepspeed执行推理的时候，显存是成倍增长，chatglm我用一张卡显存是15g，用2张卡就是30g，3张卡就是45g； 目测就是每个卡都加载了一模一样参数量的，这个也是由于chatglm无法自动层并行导致的吗？ 
使用deepspeed加载的核心代码就是这个
model = deepspeed.init_inference(
    model=model,      # Transformers models
    mp_size=2,        # Number of GPU
    dtype=torch.float16, # dtype of the weights (fp16)
    replace_method="auto", # Lets DS autmatically identify the layer to replace
    replace_with_kernel_inject=True, # replace the model with the kernel injector
)

**Comment by yuanzhoulvpi2017** [comment]
没用过deepspeed，下次研究一下
