### ISSUE TITLE
main_parallel.py 报错 print_dataset_example这里报错 preprocess_function_train错了

### ISSUE THREAD

**Issue by hangzeli08** [yuanzhoulvpi2017/zero_nlp#75]
print("inputs", tokenizer.decode(example["input_ids"]))
会报错误IndexError: Out of range: piece id is out of range
应该是preprocess_function_train这个函数有错误的地方，希望作者可以修改一下

有人遇到同样的错误并解决了吗，可告知方案吗

**Comment by yuanzhoulvpi2017** [comment]
已修复，详情查看链接[https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b#04-15-%E7%89%88%E6%9C%AC](https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b#04-15-%E7%89%88%E6%9C%AC)
