### ISSUE TITLE
显存

### ISSUE THREAD

**Issue by yangliuIOC** [yuanzhoulvpi2017/zero_nlp#78]
你好作者，为什么按照你的代码 ，batch 改成1 都不行 显存OOM

**Comment by yangliuIOC** [comment]
应该是 清华改了很多东西，作者没有跟着修改

**Comment by yuanzhoulvpi2017** [comment]
是哪一个文件夹📁出现的问题。报给我一下

**Comment by yangliuIOC** [comment]
simple_thu_chatglm6b, 这个 文件，你应该是改了model_chatglm文件，所以以前能在24G跑通，但是现在清华又在这个文件上修改了点东西，所以必须要加载清华的model_chatglm，导致你的jupyter跑不通了，能不能把优化的点放到jupyter里

**Comment by yuanzhoulvpi2017** [comment]
修复了因为官方代码发布的，导致lora方法训练模型的bug问题。朋友可以查看最新的代码https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b
