### ISSUE TITLE
EOP TOKEN ID

### ISSUE THREAD

**Issue by yangliuIOC** [yuanzhoulvpi2017/zero_nlp#79]
请问您的eop token id 是什么 id？最新版的tokenizer 没有这个ID

**Comment by StarRanger** [comment]
AttributeError: 'ChatGLMTokenizer' object has no attribute 'eop_token_id'
这个异常吗？我也遇到了，需要怎么解决？

**Comment by yuanzhoulvpi2017** [comment]
已修复，查看最新的代码https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/simple_thu_chatglm6b
