### ISSUE TITLE
[BUG]训练脚本报错

### ISSUE THREAD

**Issue by aihaidong** [yuanzhoulvpi2017/zero_nlp#85]
训练lora代码报错
AttributeError: 'ChatGLMTokenizer' object has no attribute 'eop_token_id'
[tokenizer.eop_token_id]
是不是应该改成
[tokenizer.sp_tokenizer[tokenizer.eos_token]]

**Comment by yuanzhoulvpi2017** [comment]
注意`model_name_or_path`的模型，要用我提供的模型

**Comment by kiluar2020** [comment]
找到tokenization_chatglm.py 文件，修改类 class ChatGLMTokenizer，如下：
增加下面属性，可能因为升级的原因，导致，原来的属性迁移了
    @property
    def eop_token_id(self) -> Optional[int]:
        return self.end_token_id

**Comment by yuanzhoulvpi2017** [comment]
> 

是的，官方又又又改代码了

**Comment by yuanzhoulvpi2017** [comment]
> 

不是啊，用我提供的`chatglm6b-dddd`这个版本

**Comment by kiluar2020** [comment]
这样改一下代码也能启动训练了，不过效果如何我也不知道

**Comment by mountbreeze** [comment]
这个问题应该是新版本将函数eop_token_id改成end_token_id了，改一下应该就可以了

**Comment by Fab-Liu** [comment]
transformers              4.30.2 版本无问题
