### ISSUE TITLE
训练好的ckeckpoint模型没有变化

### ISSUE THREAD

**Issue by akoukou123** [yuanzhoulvpi2017/zero_nlp#9]
遇到了非常神奇的现象，用老哥的数据原封不动训练chatglm，训练完之后用checkpoint200推理，明明loss只有0.002左右了，但是问他readme里面的问题，输出结果和原来的模型依然没有任何变化。
不知道大家有没有遇到过这种情况？

**Comment by wdkwdkwdk** [comment]
+1 我也是这样的，然后我用demo中给出的data2进行训练，但依然看不出变化

**Comment by qq31682216** [comment]
先给点个赞，期待后续

**Comment by akoukou123** [comment]
分享一下我们这边的工作：
1、翻译部分了alpaca数据集，补充了一些数据。项目地址在这里 https://github.com/hikariming/alpaca_chinese_dataset
2、把大概15个问题和回答复制了300次，重新改了下dataloader转换成chatglm的形式，只训练这15个问题，把loss降到了0.002左右，稍后我们会在https://github.com/hikariming/alpaca_chinese_dataset放出代码
3、测试训练好的模型，随便问这15个问题中的回答，依然不行

其他的额外补充，我们用了另一个只微调0.6%参数的lora方法，然后发现模型没法像老哥的项目一样收敛。

**Comment by xtc1989** [comment]
同碰到这个问题，看了下从checkpoint读的model参数和结构，没有把lora的训练结果保存到checkpoint里

**Comment by hikariming** [comment]
> 没有

我把微调仓库都试完了，目前看效果最明显的是那个用自己对话数据集的项目，但是这边项目的微调代码好清爽，我们也会继续研究问题出在哪里

**Comment by yuanzhoulvpi2017** [comment]
> 

哈哈哈，感谢老哥的夸奖，我当时数据，只是一个简单的demo。并没有做什么数据上的策略。目前并行这个大问题，我也解决了。接下来就开始优化数据了。

**Comment by BiaoLiu2017** [comment]
inference阶段代码有问题吧？只读取了原始的参数，没有读取lora参数，所以和原模型一模一样

**Comment by zhangtaochn** [comment]
#17  请问是这个问题导致预测结果和原始参数结果没变化的么，但不知道怎么改

**Comment by hikariming** [comment]
> inference阶段代码有问题吧？只读取了原始的参数，没有读取lora参数，所以和原模型一模一样

看代码似乎是读取了的....我也暂时不知道是怎么回事，我的colab没有💰了，就先这样吧，等待更厉害的大佬解决这个问题

**Comment by yanchaoguo** [comment]
初始化的时候权重更新失败
![image](https://user-images.githubusercontent.com/11827802/227955663-717c7353-0ff1-4f0b-84ac-14c28b5d5aa7.png)

**Comment by hikariming** [comment]
> 具体不多解释了。用实验数据说话，下一步，我将用来提升效果。后面会吧相关的东西放在这里

大哥加油！我们也在持续研究这个问题，有结果了也和你说

**Comment by feiwuu638** [comment]
> > 没有
> 
> 我把微调仓库都试完了，目前看效果最明显的是那个用自己对话数据集的项目，但是这边项目的微调代码好清爽，我们也会继续研究问题出在哪里

请问对话数据集是哪个项目呀 @hikariming

**Comment by hikariming** [comment]
大哥牛逼，能用上我们数据集是我们的荣幸😄
